import jsPDF from 'jspdf';
import type { UserData } from '@/hooks/useWizard';
import { decodeHtmlEntities } from '@/lib/htmlEntities';
import { buildUsefulLinksFromUserData } from '@/lib/usefulLinks';
import { localizeDesklineEventUrl } from '@/lib/desklineUrl';
import { LOGO_JESOLO_PNG_BASE64 } from '@/assets/logoJesoloBase64';

export interface VacationPlan {
  title: string;
  introduction: string;
  highlights: string[];
  days: Array<{
    date: string;
    title: string;
    slots: Array<{ time_of_day: 'morning' | 'afternoon' | 'evening' | 'full-day'; content: string }>;
    events?: Array<{ title: string; time?: string; location?: string; url?: string; image?: string }>;
  }>;
}

type SupportedLanguage = 'it' | 'en' | 'de';

const PDF_COPY: Record<SupportedLanguage, {
  fallbackTitle: string;
  portalSubtitle: string;
  travelerProfile: string;
  introduction: string;
  highlights: string;
  itinerary: string;
  summary: string;
  summaryText: string;
  name: string;
  email: string;
  origin: string;
  group: string;
  interests: string;
  footerGeneratedBy: string;
  page: string;
  slotLabels: Record<'morning' | 'afternoon' | 'evening' | 'full-day', string>;
  recommendedEvents: string;
  allDay: string;
  locale: string;
  usefulLinks: string;
  daysWord: string;
}> = {
  it: {
    fallbackTitle: 'Jesolo.it — Il tuo piano vacanza',
    portalSubtitle: 'Jesolo.it — Portale turistico di Jesolo',
    travelerProfile: 'Profilo viaggiatore',
    introduction: 'Introduzione',
    highlights: 'Highlights del viaggio',
    itinerary: 'Itinerario giorno per giorno',
    summary: 'Riepilogo',
    summaryText: 'Il tuo piano vacanza personalizzato è in preparazione. Visita jesolo.it per maggiori informazioni.',
    name: 'Nome',
    email: 'Email',
    origin: 'Provenienza',
    group: 'Gruppo',
    interests: 'Interessi',
    footerGeneratedBy: 'Generato da Jesolo.it',
    page: 'Pagina',
    slotLabels: {
      morning: 'Mattina',
      afternoon: 'Pomeriggio',
      evening: 'Sera',
      'full-day': 'Giornata intera',
    },
    recommendedEvents: 'Consigliati per la giornata',
    allDay: 'Tutto il giorno',
    locale: 'it-IT',
    usefulLinks: 'Link utili',
    daysWord: 'GIORNI',
  },
  en: {
    fallbackTitle: 'Jesolo.it — Your vacation plan',
    portalSubtitle: 'Jesolo.it — Jesolo tourism portal',
    travelerProfile: 'Traveler profile',
    introduction: 'Introduction',
    highlights: 'Trip highlights',
    itinerary: 'Day-by-day itinerary',
    summary: 'Summary',
    summaryText: 'Your personalized vacation plan is being prepared. Visit jesolo.it for more information.',
    name: 'Name',
    email: 'Email',
    origin: 'Origin',
    group: 'Group',
    interests: 'Interests',
    footerGeneratedBy: 'Generated by Jesolo.it',
    page: 'Page',
    slotLabels: {
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      'full-day': 'Full day',
    },
    recommendedEvents: 'Recommended for the day',
    allDay: 'All day',
    locale: 'en-US',
    usefulLinks: 'Useful links',
    daysWord: 'DAYS',
  },
  de: {
    fallbackTitle: 'Jesolo.it — Dein Urlaubsplan',
    portalSubtitle: 'Jesolo.it — Tourismusportal von Jesolo',
    travelerProfile: 'Reiseprofil',
    introduction: 'Einleitung',
    highlights: 'Reise-Highlights',
    itinerary: 'Tagesprogramm',
    summary: 'Zusammenfassung',
    summaryText: 'Dein persönlicher Urlaubsplan wird vorbereitet. Besuche jesolo.it für weitere Informationen.',
    name: 'Vorname',
    email: 'E-Mail',
    origin: 'Herkunft',
    group: 'Reisegruppe',
    interests: 'Interessen',
    footerGeneratedBy: 'Erstellt von Jesolo.it',
    page: 'Seite',
    slotLabels: {
      morning: 'Morgen',
      afternoon: 'Nachmittag',
      evening: 'Abend',
      'full-day': 'Ganztägig',
    },
    recommendedEvents: 'Empfehlungen für den Tag',
    allDay: 'Ganztägig',
    locale: 'de-DE',
    usefulLinks: 'Nützliche Links',
    daysWord: 'TAGE',
  },
};

function normalizeLanguage(language?: string): SupportedLanguage {
  const baseLanguage = language?.split('-')[0]?.toLowerCase();
  return baseLanguage === 'en' || baseLanguage === 'de' ? baseLanguage : 'it';
}

function sanitizePdfText(value?: string | null): string {
  if (!value) return '';

  return decodeHtmlEntities(value)
    .normalize('NFKC')
    .replace(/[\u200B-\u200D\u2060\uFE0E\uFE0F]/g, '')
    .replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}]/gu, '')
    .replace(/[•◦▪▫■□◆◇★☆▶►◀◄➜➤➔➝➞➟➠]/g, '-')
    .replace(/\s+/g, ' ')
    .trim();
}

function capitalizeFirst(value: string) {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : value;
}

function formatPdfDate(value: string, locale: string): string {
  const match = value?.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return value;
  const [, year, month, day] = match;
  const date = new Date(Date.UTC(Number(year), Number(month) - 1, Number(day)));
  const parts = new Intl.DateTimeFormat(locale, {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).formatToParts(date);
  return parts
    .map((p) => {
      if (p.type === 'literal') return p.value;
      return p.type === 'weekday' || p.type === 'month' ? capitalizeFirst(p.value) : p.value;
    })
    .join('')
    .trim();
}

function isAllDayTime(value?: string): boolean {
  if (!value) return false;
  return /^00:?00(:00)?$/.test(value.trim());
}

export function generatePdf(userData: UserData, plan?: VacationPlan | null, language?: string): Blob {
  const copy = PDF_COPY[normalizeLanguage(language)];
  const lang = normalizeLanguage(language);
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const PAGE_W = 210;
  const PAGE_H = 297;
  const MARGIN = 16;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  const BOTTOM_LIMIT = PAGE_H - 18; // leave room for footer

  // Color tokens (from the reference design)
  const INK: [number, number, number] = [26, 35, 48];
  const INK2: [number, number, number] = [74, 86, 102];
  const MUTED: [number, number, number] = [139, 149, 163];
  const RULE: [number, number, number] = [229, 232, 236];
  const DAY_COLORS: [number, number, number][] = [
    [210, 52, 43],   // red
    [232, 185, 57],  // gold
    [46, 156, 160],  // teal
    [42, 143, 208],  // blue
    [224, 137, 86],  // coral
    [28, 61, 82],    // navy
  ];

  const setFill = (c: [number, number, number]) => doc.setFillColor(c[0], c[1], c[2]);
  const setDraw = (c: [number, number, number]) => doc.setDrawColor(c[0], c[1], c[2]);
  const setText = (c: [number, number, number]) => doc.setTextColor(c[0], c[1], c[2]);

  let y = MARGIN;
  let pageNum = 1;
  // We'll fill footer page totals at the end
  const footerYs: { page: number }[] = [];

  const drawMasthead = (continued = false) => {
    // Jesolo logo image (318 x 66 px source)
    const logoH = 8;
    const logoW = logoH * (318 / 66);
    try {
      doc.addImage(LOGO_JESOLO_PNG_BASE64, 'PNG', MARGIN, MARGIN, logoW, logoH);
    } catch {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      setText(INK);
      doc.text('JESOLO', MARGIN, MARGIN + 6);
    }
    // Right block
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    setText(MUTED);
    const rightLabel = continued
      ? `${copy.fallbackTitle.toUpperCase()} · ${copy.itinerary.toUpperCase()}`
      : copy.fallbackTitle.toUpperCase();
    doc.text(rightLabel, PAGE_W - MARGIN, MARGIN + 2, { align: 'right' });
    // Bottom rule
    setDraw(INK);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, MARGIN + 12, PAGE_W - MARGIN, MARGIN + 12);
    y = MARGIN + 18;
  };

  const drawFooter = (pageIndex: number, totalPages: number) => {
    const fy = PAGE_H - 12;
    setDraw(INK);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, fy - 4, PAGE_W - MARGIN, fy - 4);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    setText(MUTED);
    doc.text(copy.footerGeneratedBy.toUpperCase(), MARGIN, fy);
    setText(INK);
    doc.setFont('helvetica', 'bold');
    doc.text(`${copy.page.toUpperCase()} ${pageIndex} / ${totalPages}`, PAGE_W - MARGIN, fy, { align: 'right' });
  };

  const newPage = (continued = true) => {
    doc.addPage();
    pageNum += 1;
    y = MARGIN;
    drawMasthead(continued);
  };

  const ensure = (h: number) => {
    if (y + h > BOTTOM_LIMIT) newPage(true);
  };

  // ── Page 1 masthead ──────────────────────────────────────────────────────
  drawMasthead(false);

  // ── Hero ────────────────────────────────────────────────────────────────
  const days = plan?.days ?? [];
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  setText(DAY_COLORS[0]);
  const eyebrow = `${copy.itinerary.toUpperCase()} · ${days.length || ''} ${copy.daysWord}`.replace('  ', ' ').trim();
  doc.text(eyebrow, MARGIN, y + 4);
  y += 8;

  // Title
  const title = sanitizePdfText(plan?.title) || copy.fallbackTitle;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  setText(INK);
  const titleLines = doc.splitTextToSize(title, CONTENT_W);
  doc.text(titleLines, MARGIN, y + 8);
  y += titleLines.length * 10 + 4;

  y += 4;

  // ── Traveler card ───────────────────────────────────────────────────────
  type Cell = { k: string; v: string; sub?: string };
  const fullName = `${userData.name ?? ''} ${userData.surname ?? ''}`.trim();
  const originParts = [userData.province || userData.city, userData.country].filter(Boolean) as string[];
  const groupLabel = userData.travelGroup ? capitalizeFirst(sanitizePdfText(userData.travelGroup)) : '';
  const groupSub = userData.hasPet ? '+ dog' : '';
  const interestList = (userData.interests ?? []).map((s) => sanitizePdfText(s)).filter(Boolean);
  const lifestyleList = ((userData as unknown as { lifestyle?: string[] }).lifestyle ?? []).map((s) => sanitizePdfText(s)).filter(Boolean);

  const cells: Cell[] = [];
  if (fullName || userData.email) cells.push({ k: 'TRAVELER', v: fullName || '—', sub: sanitizePdfText(userData.email) });
  if (originParts.length) cells.push({ k: 'ORIGIN', v: sanitizePdfText(originParts.join(', ')) });
  if (groupLabel) cells.push({ k: 'GROUP', v: groupLabel, sub: groupSub });
  if (interestList.length) cells.push({ k: 'INTERESTS', v: interestList.map(capitalizeFirst).join(', ') });
  if (lifestyleList.length) cells.push({ k: 'LIFESTYLE', v: lifestyleList.map(capitalizeFirst).join(', ') });

  if (cells.length) {
    const cols = cells.length;
    const cellW = CONTENT_W / cols;
    // Compute row height based on tallest cell
    let maxH = 12;
    const measured = cells.map((c) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      const vLines = doc.splitTextToSize(c.v, cellW - 6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      const sLines = c.sub ? doc.splitTextToSize(c.sub, cellW - 6) : [];
      const h = 4 + vLines.length * 4.2 + sLines.length * 3.8 + 4;
      if (h > maxH) maxH = h;
      return { vLines, sLines };
    });
    ensure(maxH + 4);
    // Card border
    setDraw(RULE);
    doc.setLineWidth(0.3);
    doc.rect(MARGIN, y, CONTENT_W, maxH);
    cells.forEach((c, i) => {
      const cx = MARGIN + i * cellW;
      if (i > 0) doc.line(cx, y, cx, y + maxH);
      // Key
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.8);
      setText(MUTED);
      doc.text(c.k, cx + 3, y + 4.5);
      // Value
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      setText(INK);
      doc.text(measured[i].vLines, cx + 3, y + 9);
      // Sub
      if (measured[i].sLines.length) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        setText(INK2);
        doc.text(measured[i].sLines, cx + 3, y + 9 + measured[i].vLines.length * 4.2 + 1);
      }
    });
    y += maxH + 8;
  }

  // ── Section header: Day-by-day itinerary ────────────────────────────────
  const drawSectionHeader = (title: string, meta = '') => {
    ensure(22);
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    setText(INK);
    doc.text(title, MARGIN, y);
    if (meta) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      setText(MUTED);
      doc.text(meta.toUpperCase(), PAGE_W - MARGIN, y, { align: 'right' });
    }
    y += 3;
    setDraw(RULE);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 9;
  };

  if (days.length) {
    drawSectionHeader(copy.itinerary);
  } else if (plan?.highlights?.length) {
    drawSectionHeader(copy.highlights);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    setText(INK2);
    for (const h of plan.highlights) {
      const t = sanitizePdfText(h);
      if (!t) continue;
      const lines = doc.splitTextToSize(`• ${t}`, CONTENT_W);
      ensure(lines.length * 5 + 1);
      doc.text(lines, MARGIN, y);
      y += lines.length * 5 + 1;
    }
  } else {
    drawSectionHeader(copy.summary);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    setText(INK2);
    const lines = doc.splitTextToSize(sanitizePdfText(copy.summaryText), CONTENT_W);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5;
  }

  // ── Render each day ─────────────────────────────────────────────────────
  const shortWeekday = (date: string) => {
    const m = date.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (!m) return '';
    const d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3]));
    const parts = new Intl.DateTimeFormat(copy.locale, { weekday: 'long', day: 'numeric', month: 'long', timeZone: 'UTC' }).formatToParts(d);
    return parts.map((p) => p.type === 'literal' ? p.value : (p.type === 'weekday' || p.type === 'month' ? capitalizeFirst(p.value.replace(/\./g, '')) : p.value)).join('').trim();
  };

  const drawDayHeader = (idx: number, d: NonNullable<VacationPlan['days']>[number]) => {
    const color = DAY_COLORS[idx % DAY_COLORS.length];
    const dayLabel = `${(copy.itinerary === 'Tagesprogramm' ? 'Tag' : (lang === 'it' ? 'Giorno' : 'Day'))} ${idx + 1}`;
    const dateLabel = shortWeekday(d.date);
    const title = sanitizePdfText(d.title);

    // Measure left block width: dot + day label + date label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    const dayLabelW = doc.getTextWidth(dayLabel);
    const dotOffset = 6;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    const titleLines = doc.splitTextToSize(title, CONTENT_W);
    const headerH = 6 + titleLines.length * 5 + 2;
    ensure(headerH + 4);

    // Colored dot
    setFill(color);
    doc.circle(MARGIN + 1.8, y + 2.6, 1.4, 'F');
    // Day label (left)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    setText(color);
    doc.text(dayLabel, MARGIN + dotOffset, y + 4);
    // Date label (after day)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    setText(MUTED);
    doc.text(dateLabel.toUpperCase(), MARGIN + dotOffset + dayLabelW + 4, y + 4);
    // Title (new line, left aligned)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    setText(INK);
    doc.text(titleLines, MARGIN, y + 10);
    y += headerH + 5;
  };

  const drawSlots = (d: NonNullable<VacationPlan['days']>[number]) => {
    const slots = (d.slots ?? []).filter((s) => sanitizePdfText(s.content));
    if (!slots.length) return;
    const cols = Math.min(3, slots.length);
    const gutter = 5;
    const colW = (CONTENT_W - gutter * (cols - 1)) / cols;

    // Process in rows of up to `cols`
    for (let i = 0; i < slots.length; i += cols) {
      const row = slots.slice(i, i + cols);
      // Measure max height
      const measured = row.map((s) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        const lines = doc.splitTextToSize(sanitizePdfText(s.content), colW);
        return lines;
      });
      const rowH = Math.max(...measured.map((l) => l.length * 4.5)) + 8;
      ensure(rowH + 2);
      row.forEach((s, j) => {
        const cx = MARGIN + j * (colW + gutter);
        // Slot label
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        setText(INK);
        doc.text((copy.slotLabels[s.time_of_day] ?? s.time_of_day).toUpperCase(), cx, y);
        // Body
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        setText(INK2);
        doc.text(measured[j], cx, y + 6);
      });
      y += rowH + 2;
    }
  };

  const drawRecs = (d: NonNullable<VacationPlan['days']>[number], colorIdx: number) => {
    const events = (d.events ?? []).filter((e) => sanitizePdfText(e.title));
    if (!events.length) return;
    const color = DAY_COLORS[colorIdx % DAY_COLORS.length];
    ensure(8);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    setText(INK);
    doc.text(copy.recommendedEvents.toUpperCase(), MARGIN, y);
    y += 3;
    setDraw(RULE);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 1;

    const whenW = 32;
    const tagW = 24;
    const infoW = CONTENT_W - whenW - tagW - 8;
    for (const ev of events) {
      const evTitle = sanitizePdfText(ev.title);
      const time = ev.time ? (isAllDayTime(ev.time) ? copy.allDay : sanitizePdfText(ev.time)) : '';
      const loc = sanitizePdfText(ev.location);
      const when = [time, loc].filter(Boolean).join(' · ');
      const url = ev.url ? sanitizePdfText(localizeDesklineEventUrl(ev.url, lang) ?? ev.url) : '';

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      const titleLines = doc.splitTextToSize(evTitle, infoW);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      const urlLines = url ? doc.splitTextToSize(url, infoW) : [];
      const rowH = Math.max(8, titleLines.length * 4.5 + urlLines.length * 3.5 + 4);
      ensure(rowH + 1);

      // When column
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      setText(INK);
      doc.text(doc.splitTextToSize(when || '—', whenW), MARGIN, y + 3);
      // Info column
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      setText(INK);
      const infoX = MARGIN + whenW + 4;
      doc.text(titleLines, infoX, y + 3);
      if (url) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        setText(MUTED);
        let uy = y + 3 + titleLines.length * 4.5;
        for (const line of urlLines) {
          doc.textWithLink(line, infoX, uy, { url });
          uy += 3.5;
        }
      }
      y += rowH;
      setDraw(RULE);
      doc.setLineWidth(0.3);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y);
      y += 1;
    }
    y += 2;
  };

  days.forEach((d, idx) => {
    drawDayHeader(idx, d);
    drawSlots(d);
    drawRecs(d, idx);
    y += 6;
  });

  // ── Useful links ────────────────────────────────────────────────────────
  const usefulLinks = buildUsefulLinksFromUserData(userData, language);
  if (usefulLinks.length) {
    y += 2;
    drawSectionHeader(copy.usefulLinks);
    for (const link of usefulLinks) {
      const labelText = sanitizePdfText(link.label);
      const urlText = sanitizePdfText(link.url);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      setText(INK);
      const labelLines = doc.splitTextToSize(labelText, CONTENT_W);
      const urlLines = doc.splitTextToSize(urlText, CONTENT_W);
      const h = labelLines.length * 4.5 + urlLines.length * 4 + 4;
      ensure(h);
      doc.text(labelLines, MARGIN, y);
      y += labelLines.length * 4.5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      setText(MUTED);
      for (const line of urlLines) {
        doc.textWithLink(line, MARGIN, y, { url: urlText });
        y += 4;
      }
      y += 3;
    }
  }

  // ── Footer on every page ────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }
  void footerYs;

  return doc.output('blob');
}
