// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikjsfzgahlncfnjtqfem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlranNmemdhaGxuY2ZuanRxZmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MzIyODYsImV4cCI6MjA5MjAwODI4Nn0.lESjRAEFuJ6Tjuz1r98De3O6cbmuWlkteZtYolJpvGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});